name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  DISCORD_CLIENT_ID: "astrid is pretty"
  DISCORD_BOT_TOKEN: "<3"
  DISCORD_PUBLIC_KEY: "i love her"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
